language: php
dist: trusty
sudo: false
install: true
script: true
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: dev
env:
  global:
    - WEBSITE=test.internetguru.cz
    - secure: "NMAUQsSUO+sR+rQ/92A7z+Kx4xi/2YbuaDumWUms+wCOgq8Fv+chclhHqPgDwddakx0UhKY0UpKArOWOZvPQxIx523PVLkxw4ZLbIWeFUnoQgammpXlW9iJ7+oboC3LfYSU8an9sRCzTOQovtTDnGjCpkuio4ZMtdBxMCTNvQDXuq5hZPAxIaOyuXaD6AqTSn4BpUethJyhxHAZj3pGipvywAuFFMRbwLuYlSAaEfY8X/E57tiAPv4E+VH33cAwSplthHq4HUKigA/ya0NRMWy0+g1Ne7XcvNZsPHOHK+IyMhEZxrgbXCz5yEW+LwmHxwp82YRcGJ20fcwRtnGvBWYa+XuAtEhmHJ0MBbE+uZhhSt6at//uZzzozzL7tQ/Tly7FNFrIZjyeGd5zb8qI6BchSG3YqW+tt/VxVIfPUqh8QvNu5RKb581HZL1pkmb0QQCUzIFnMJKZArhlU5e9JAMpNCefhc++ZEoJ82G5onyYQRjn8nIaccvKOjCMD/aLYg8DU9yCYSp/QGtXl7i7sUd+wjRIfUimNAzuFA07XAgPq+A4qv+oDE1EyoHHY6AoyZo3LDLfjpA0la/tt29tFKSRdy0FIvuJCBJlhWu0m0o4Tc8+VW1cEFR+XVXvhvkDgsKbNhwYRy0bQvU78YDX/dUnQknXZHYuYx/2aSwE0eIE="
    - secure: "RytO0yEo/WHItAMFu0elSojqwH4RUlJpudCM8+GvoeqiyOZMhT6K7UHBTvrQG8woly17veF01GqZlPKjfn4yJl0URhhCY73IjRzWk8gclClSt4oHkD5HrcyQ68UYig+eBSwcOchVOUTEqr+y2L5um2Bep9H7ZNjSvXJi+419rCoAKXbMWryi/fn1vuHGGT32iGAvavPQSphkdyorgoPBZp1RH1eJY9JI960l/mvfuh0xpM6tll3LLymlOuWe663YNqrX0zQ1a2X6uw4eLPCJEtiztLAydE8mEeyfC+cZX3D3Qfc33nzmiVqKgkF1RkfNL3px67DsA5QyAnXmKZqQEaJ9ItD4Lsz1HF6MFgWfMSRUmjo6+RzIsqjj/S1AEs7Sk4+sv++NAYV4dHufq/ZUWc22+r+5InnE+wHnmy0J/aHpkk4R4ezkl6M4USz3sJjAMfPq54XYiWDNqFbelZ//ivxZ0h3T1XA1ZB6thoxdcAvit3HDuvKDiB7LaSaGFYmSW77RqVSEYwccBBnCfDMHDF7JUNO/N/9RJzNq62VQtGVpnIIMA6S+4xMRhuEZ5OjPTlBKMFpS1+tI0oFKCS79lekB7bKFhB2HQ8dIFFIooqImrqNN+2TX2ZZGGZI6RX6sPOqataEFUFOESLgrVtAsM5or9AiBcNYoLoaQiHZgtVo="  
