language: ruby
dist: trusty
sudo: false

install: true
script: true

deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: dev

env:
  global:
    - WEBSITE=test.internetguru.cz
    - secure: "NMAUQsSUO+sR+rQ/92A7z+Kx4xi/2YbuaDumWUms+wCOgq8Fv+chclhHqPgDwddakx0UhKY0UpKArOWOZvPQxIx523PVLkxw4ZLbIWeFUnoQgammpXlW9iJ7+oboC3LfYSU8an9sRCzTOQovtTDnGjCpkuio4ZMtdBxMCTNvQDXuq5hZPAxIaOyuXaD6AqTSn4BpUethJyhxHAZj3pGipvywAuFFMRbwLuYlSAaEfY8X/E57tiAPv4E+VH33cAwSplthHq4HUKigA/ya0NRMWy0+g1Ne7XcvNZsPHOHK+IyMhEZxrgbXCz5yEW+LwmHxwp82YRcGJ20fcwRtnGvBWYa+XuAtEhmHJ0MBbE+uZhhSt6at//uZzzozzL7tQ/Tly7FNFrIZjyeGd5zb8qI6BchSG3YqW+tt/VxVIfPUqh8QvNu5RKb581HZL1pkmb0QQCUzIFnMJKZArhlU5e9JAMpNCefhc++ZEoJ82G5onyYQRjn8nIaccvKOjCMD/aLYg8DU9yCYSp/QGtXl7i7sUd+wjRIfUimNAzuFA07XAgPq+A4qv+oDE1EyoHHY6AoyZo3LDLfjpA0la/tt29tFKSRdy0FIvuJCBJlhWu0m0o4Tc8+VW1cEFR+XVXvhvkDgsKbNhwYRy0bQvU78YDX/dUnQknXZHYuYx/2aSwE0eIE="
    - secure: "LANIe+HnlBWzjA6lz4ZDQmpNu/GxetySaucnPGxRRbkDQNKX1SUdpFWtItq1RWd1MojdfXKlCuqK8NgkPzL/FCxVUU1eRRHsK1OeZK6iVS5jjnrKCSOvEoAxrdWfuvU33Uguw02oC530bWZwdP2aiT7iSPS6mDLLocvY4iwflX9RUCcR/O5HcJzpoqd8h2v9HLACNtYtZl/OXh2nwcQK2ACbKJM+E6WFK9vicynOso9RkN7KMjsuOCJRPf65g2my3H0XIIVYN22Ww8VPq1S9+Q5j2U2rCoxSNWHnhKuGVbQDjjVBPJE0QqqvMn1MfiE2J3j+3HwvMq0J7aIiRp+WN7PUBU0BR2bbidCc0Dild7yf45PEqNCgwvSaP0fVeK+4E0Iin1wSgrIiPHjmYfxdtsMx+Wh+USOdcFmuj29ySXaiJEfxglOeiMs8Crm7EfsJXqiepS9lyyeBIjn8dG2AoTI27zkbc5hFhicgqqtUWrORhc9oaRmOQ3RDasAyKAiiJcXPVQ3/NC+paKV72LaEjJ7UbzqNYOiZaHyygT6YqUSkZZE5c4pfW7IGXuQ5XcnQjFh6k06MazwUOiTlAu2IqTpsmvQXG6HkW9k76hrEpfB48uk7jAu176kPs+OuPD2b//WTyd3DtWxNwJaYeZ3zorFqm/YgG0tGl4nX8xUQTnQ="
